name: Build AYCriptoCan

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "CHANGELOG.md", "release-notes.md" ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        lazarus-versions: [stable]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3
      with:
        with-cache: false
        lazarus-version: ${{ matrix.lazarus-versions }}

    - name: Build Daemon
      run: lazbuild -B "src/pascalcoin_daemon.lpi"

    - name: Build Miner
      run: lazbuild -B "src/pascalcoin_miner.lpi"

    - name: Build Wallet
      if: matrix.operating-system != 'macos-latest'
      run: lazbuild -B "src/pascalcoin_wallet_classic.lpi"

    - name: Build Wallet macOS
      if: matrix.operating-system == 'macos-latest'
      run: lazbuild -B --ws=cocoa "src/pascalcoin_wallet_classic.lpi"

    - name: Prepare Windows Artifacts
      if: matrix.operating-system == 'windows-latest'
      run: |
        mkdir -p windows_artifacts
        copy src\pascalcoin_daemon.exe windows_artifacts\
        copy src\PascalCoinMiner.exe windows_artifacts\
        copy src\PascalCoinWalletLazarus.exe windows_artifacts\
        copy windows-dll\*.dll windows_artifacts\

    - name: Upload Ubuntu binary
      if: matrix.operating-system == 'ubuntu-latest'
      uses: actions/upload-artifact@v5
      with:
        name: AYCriptoCan-Linux
        path: |
          src/pascalcoin_daemon
          src/PascalCoinMiner
          src/PascalCoinWalletLazarus

    - name: Upload Windows binary
      if: matrix.operating-system == 'windows-latest'
      uses: actions/upload-artifact@v5
      with:
        name: AYCriptoCan-Windows
        path: windows_artifacts\

    - name: Upload macOS binary
      if: matrix.operating-system == 'macos-latest'
      uses: actions/upload-artifact@v5
      with:
        name: AYCriptoCan-macOS
        path: |
          src/pascalcoin_daemon
          src/PascalCoinMiner
          src/PascalCoinWalletLazarus